spring.application.name=spring_security_jvt

#db
spring.datasource.url = ${MYSQL_URL}
spring.datasource.username=${MYSQL_USERNAME}
spring.datasource.password=${MYSQL_PASSWORD}


#jpa
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.servlet.context-path=/api

#swagger
springdoc.api-docs.path=/api-docs


